'use strict';

/**
 * PHP template engine for Shiplet.
 *
 * Supports:
 *   - vanilla php (blank PHP project)
 *   - laravel      (Laravel 11 with Artisan, queues, scheduler)
 *   - symfony      (Symfony 7 with console commands)
 *   - wordpress    (WordPress with WP-CLI)
 *   - slim         (Slim Framework 4)
 *   - lumen        (Lumen micro-framework)
 *
 * Runtimes: docker | podman
 */

// ── PHP version → base image map ─────────────────────────────────────────────
const PHP_IMAGES = {
    '8.3': 'php:8.3-fpm-bookworm',
    '8.2': 'php:8.2-fpm-bookworm',
    '8.1': 'php:8.1-fpm-bookworm',
    '8.0': 'php:8.0-fpm-buster',
};

// ── Extension sets by template ────────────────────────────────────────────────
const PHP_EXTENSIONS = {
    laravel: ['pdo', 'pdo_mysql', 'pdo_pgsql', 'redis', 'gd', 'zip', 'bcmath', 'opcache', 'pcntl', 'mbstring', 'xml', 'intl', 'exif'],
    symfony: ['pdo', 'pdo_mysql', 'pdo_pgsql', 'redis', 'gd', 'zip', 'intl', 'opcache', 'mbstring', 'xml', 'sockets'],
    wordpress: ['pdo', 'mysql', 'mysqli', 'gd', 'zip', 'mbstring', 'xml', 'curl', 'imagick'],
    slim: ['pdo', 'pdo_mysql', 'pdo_pgsql', 'mbstring', 'opcache'],
    lumen: ['pdo', 'pdo_mysql', 'pdo_pgsql', 'redis', 'mbstring', 'opcache'],
    blank: ['pdo', 'pdo_mysql', 'pdo_pgsql', 'mbstring', 'opcache'],
};

// ── Generate compose.yml for PHP projects ─────────────────────────────────────
function generatePhpCompose(answers) {
    const {
        appName, template, phpVersion = '8.3',
        port = 80, services = [], timezone = 'UTC',
        webServer = 'nginx',
    } = answers;

    const name = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-');
    const appPort = port;

    // Web server (nginx or apache)
    const webServerBlock = webServer === 'apache'
        ? apacheBlock(appPort)
        : nginxBlock(appPort);

    const serviceBlocks = services
        .map(s => phpServiceSnippet(s))
        .filter(Boolean)
        .map(s => indent(s, 2))
        .join('\n\n');

    const depends = services.length
        ? `\n    depends_on:\n${services.map(s => `      - ${s}`).join('\n')}`
        : '';

    const templateEnvBlock = phpTemplateEnvInCompose(template);

    const hasVolumes = services.filter(s => PHP_VOLUME_SERVICES.has(s));
    const volBlock = [
        ...hasVolumes.map(s => `  ${s}_data:\n    driver: local`),
        `  composer_cache:\n    driver: local`,
    ].join('\n');

    return `# Generated by Shiplet — PHP/${template} project
# Runtime: ${answers.runtime || 'docker'}
# PHP: ${phpVersion}  Web: ${webServer}
#
# Commands:
#   shiplet up -d                   Start everything
#   shiplet composer install        Install PHP deps
#   shiplet php artisan migrate     Run Artisan commands (Laravel)
#   shiplet php bin/console         Run Symfony console
#   shiplet shell                   Shell into app container
#   shiplet db                      Open database CLI

name: ${name}

services:
  # ── PHP Application (FPM) ──────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: .shiplet/Dockerfile
      args:
        PHP_VERSION: "${phpVersion}"
        TZ: "${timezone}"
    image: ${name}/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ".:/var/www/html"
      - "composer_cache:/root/.composer/cache"
    networks:
      - shiplet${templateEnvBlock}${depends}
    restart: unless-stopped

  # ── Web Server ─────────────────────────────────────────────────────────────
  ${webServerBlock}

${serviceBlocks}

volumes:
${volBlock}

networks:
  shiplet:
    driver: bridge
`;
}

function nginxBlock(appPort) {
    return `nginx:
    image: "nginx:alpine"
    ports:
      - "\${APP_PORT:-${appPort}}:80"
    volumes:
      - ".:/var/www/html:ro"
      - "./.shiplet/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
    networks:
      - shiplet
    depends_on:
      - app
    restart: unless-stopped`;
}

function apacheBlock(appPort) {
    return `apache:
    image: "httpd:2.4-alpine"
    ports:
      - "\${APP_PORT:-${appPort}}:80"
    volumes:
      - ".:/var/www/html:ro"
      - "./.shiplet/apache/vhost.conf:/usr/local/apache2/conf/extra/httpd-vhost.conf:ro"
    networks:
      - shiplet
    depends_on:
      - app
    restart: unless-stopped`;
}

function phpTemplateEnvInCompose(template) {
    const envMap = {
        laravel: `
    environment:
      APP_ENV:    "\${APP_ENV:-local}"
      APP_KEY:    "\${APP_KEY}"
      APP_DEBUG:  "\${APP_DEBUG:-true}"
      DB_CONNECTION: "\${DB_CONNECTION:-mysql}"
      CACHE_DRIVER:  "redis"
      QUEUE_CONNECTION: "redis"
      SESSION_DRIVER: "redis"`,
        symfony: `
    environment:
      APP_ENV:    "\${APP_ENV:-dev}"
      APP_SECRET: "\${APP_SECRET}"
      DATABASE_URL: "\${DATABASE_URL}"`,
        wordpress: `
    environment:
      WORDPRESS_DB_HOST:     "mysql"
      WORDPRESS_DB_USER:     "\${MYSQL_USER:-shiplet}"
      WORDPRESS_DB_PASSWORD: "\${MYSQL_PASSWORD:-secret}"
      WORDPRESS_DB_NAME:     "\${MYSQL_DATABASE:-wordpress}"`,
        blank: '',
        slim: `
    environment:
      APP_ENV: "\${APP_ENV:-development}"`,
        lumen: `
    environment:
      APP_ENV:   "\${APP_ENV:-local}"
      APP_DEBUG: "\${APP_DEBUG:-true}"`,
    };
    return envMap[template] || '';
}

const PHP_VOLUME_SERVICES = new Set(['mysql', 'postgres', 'mongo', 'redis', 'minio', 'elasticsearch']);

function phpServiceSnippet(name) {
    // Re-use the same snippets from the Node templates, plus a few PHP-specific ones
    const snippets = {
        mysql: `mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: "\${MYSQL_ROOT_PASSWORD:-secret}"
      MYSQL_DATABASE:      "\${MYSQL_DATABASE:-app}"
      MYSQL_USER:          "\${MYSQL_USER:-shiplet}"
      MYSQL_PASSWORD:      "\${MYSQL_PASSWORD:-secret}"
    ports:
      - "\${MYSQL_PORT:-3306}:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 5s
      retries: 10`,

        postgres: `postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER:     "\${POSTGRES_USER:-shiplet}"
      POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD:-secret}"
      POSTGRES_DB:       "\${POSTGRES_DB:-app}"
    ports:
      - "\${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-shiplet}"]
      interval: 5s
      retries: 10`,

        redis: `redis:
    image: "redis:7-alpine"
    ports:
      - "\${REDIS_PORT:-6379}:6379"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10`,

        mailpit: `mailpit:
    image: "axllent/mailpit"
    ports:
      - "\${MAILPIT_SMTP_PORT:-1025}:1025"
      - "\${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - shiplet`,

        minio: `minio:
    image: "minio/minio"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER:     "\${MINIO_ROOT_USER:-shiplet}"
      MINIO_ROOT_PASSWORD: "\${MINIO_ROOT_PASSWORD:-secretsecret}"
    ports:
      - "\${MINIO_PORT:-9000}:9000"
      - "\${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - "minio_data:/data"
    networks:
      - shiplet`,

        elasticsearch: `elasticsearch:
    image: "elasticsearch:8.12.2"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "\${ELASTICSEARCH_PORT:-9200}:9200"
    networks:
      - shiplet`,

        adminer: `adminer:
    image: "adminer"
    ports:
      - "\${ADMINER_PORT:-8080}:8080"
    networks:
      - shiplet`,

        phpmyadmin: `phpmyadmin:
    image: "phpmyadmin:latest"
    environment:
      PMA_HOST: "mysql"
      PMA_USER: "\${MYSQL_USER:-shiplet}"
      PMA_PASSWORD: "\${MYSQL_PASSWORD:-secret}"
    ports:
      - "\${PMA_PORT:-8081}:80"
    networks:
      - shiplet`,
    };
    return snippets[name] || null;
}

// ── Generate Dockerfile for PHP projects ──────────────────────────────────────
function generatePhpDockerfile(answers) {
    const {
        template = 'blank',
        phpVersion = '8.3',
        timezone = 'UTC',
    } = answers;

    const baseImage = PHP_IMAGES[phpVersion] || PHP_IMAGES['8.3'];
    const extensions = PHP_EXTENSIONS[template] || PHP_EXTENSIONS.blank;
    const pecl = ['redis', 'imagick', 'xdebug'].filter(e => extensions.includes(e));
    const dockerExt = extensions.filter(e => !pecl.includes(e));

    const installPecl = pecl.length
        ? `\n# PECL extensions\nRUN pecl install ${pecl.join(' ')} \\\n && docker-php-ext-enable ${pecl.join(' ')}`
        : '';

    const templateSetup = phpTemplateDockerSetup(template);
    const workerSetup = template === 'laravel' ? laravelWorkerSetup() : '';
    const supervisorSetup = template === 'laravel' ? laravelSupervisorConfig() : '';

    return `# Auto-generated by Shiplet
# Language: PHP ${phpVersion}  Template: ${template}
ARG PHP_VERSION=${phpVersion}
FROM ${baseImage}

ARG TZ=UTC
ENV TZ=\${TZ} DEBIAN_FRONTEND=noninteractive

# System dependencies
RUN apt-get update -y \\
 && apt-get install -y --no-install-recommends \\
      curl git unzip zip libzip-dev libpng-dev libjpeg-dev \\
      libfreetype6-dev libpq-dev libonig-dev libxml2-dev \\
      libicu-dev libmagickwand-dev ca-certificates tzdata \\
      supervisor procps \\
 && ln -snf /usr/share/zoneinfo/\$TZ /etc/localtime \\
 && echo "\$TZ" > /etc/timezone \\
 && apt-get clean && rm -rf /var/lib/apt/lists/*

# PHP core extensions
RUN docker-php-ext-configure gd --with-freetype --with-jpeg 2>/dev/null || docker-php-ext-configure gd \\
 && docker-php-ext-install -j\$(nproc) \\
      ${dockerExt.join(' \\\n      ')}${installPecl}

# Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# PHP config
COPY .shiplet/php/php.ini \${PHP_INI_DIR}/conf.d/99-shiplet.ini
${workerSetup}
${templateSetup}
WORKDIR /var/www/html

CMD ["php-fpm"]
`;
}

function laravelWorkerSetup() {
    return `# Supervisor config for Laravel queues + scheduler
COPY .shiplet/supervisor/supervisord.conf /etc/supervisor/conf.d/supervisord.conf`;
}

function laravelSupervisorConfig() { return ''; } // content written separately

function phpTemplateDockerSetup(template) {
    const map = {
        laravel: `# Laravel artisan completion\nRUN echo 'alias art="php artisan"' >> /root/.bashrc`,
        symfony: `# Symfony console completion\nRUN echo 'alias console="php bin/console"' >> /root/.bashrc`,
        wordpress: `# WP-CLI\nRUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \\\n && chmod +x /usr/local/bin/wp`,
        blank: '',
        slim: '',
        lumen: '',
    };
    return map[template] || '';
}

// ── .env additions for PHP projects ──────────────────────────────────────────
function generatePhpEnvAdditions(answers) {
    const { template, port = 80, timezone = 'UTC', services = [], phpVersion = '8.3' } = answers;

    const lines = [
        `# Shiplet — PHP/${template}`,
        `APP_PORT=${port}`,
        `APP_ENV=local`,
        `TZ=${timezone}`,
        `PHP_VERSION=${phpVersion}`,
        '',
    ];

    if (template === 'laravel') {
        lines.push(
            '# Laravel',
            'APP_KEY=',
            'APP_DEBUG=true',
            'APP_URL=http://localhost',
            'DB_CONNECTION=mysql',
            'LOG_CHANNEL=stack',
            'BROADCAST_DRIVER=log',
            'CACHE_DRIVER=redis',
            'FILESYSTEM_DISK=local',
            'QUEUE_CONNECTION=redis',
            'SESSION_DRIVER=redis',
            'SESSION_LIFETIME=120',
            '',
        );
    }

    if (template === 'symfony') {
        lines.push('# Symfony', 'APP_SECRET=change-me-in-production', '');
    }

    if (template === 'wordpress') {
        lines.push('# WordPress', 'WP_DEBUG=true', 'WP_DEBUG_LOG=true', '');
    }

    if (services.includes('mysql')) {
        lines.push('# MySQL', 'MYSQL_ROOT_PASSWORD=secret', 'MYSQL_DATABASE=app', 'MYSQL_USER=shiplet', 'MYSQL_PASSWORD=secret', 'MYSQL_PORT=3306', '');
        if (template === 'laravel') lines.push('DB_HOST=mysql', 'DB_PORT=3306', 'DB_DATABASE=app', 'DB_USERNAME=shiplet', 'DB_PASSWORD=secret', '');
        if (template === 'symfony') lines.push('DATABASE_URL=mysql://shiplet:secret@mysql:3306/app', '');
    }

    if (services.includes('postgres')) {
        lines.push('# PostgreSQL', 'POSTGRES_USER=shiplet', 'POSTGRES_PASSWORD=secret', 'POSTGRES_DB=app', 'POSTGRES_PORT=5432', '');
        if (template === 'laravel') lines.push('DB_HOST=postgres', 'DB_PORT=5432', 'DB_DATABASE=app', 'DB_USERNAME=shiplet', 'DB_PASSWORD=secret', '');
        if (template === 'symfony') lines.push('DATABASE_URL=postgresql://shiplet:secret@postgres:5432/app', '');
    }

    if (services.includes('redis')) {
        lines.push('# Redis', 'REDIS_HOST=redis', 'REDIS_PORT=6379', 'REDIS_PASSWORD=null', '');
    }

    if (services.includes('mailpit')) {
        lines.push('# Mailpit (email)', 'MAIL_MAILER=smtp', 'MAIL_HOST=mailpit', 'MAIL_PORT=1025', 'MAIL_USERNAME=null', 'MAIL_PASSWORD=null', 'MAIL_ENCRYPTION=null', 'MAIL_FROM_ADDRESS=hello@example.com', 'MAIL_FROM_NAME="${APP_NAME}"', '');
    }

    if (services.includes('minio')) {
        lines.push('# MinIO (S3)', 'FILESYSTEM_DISK=s3', 'AWS_ACCESS_KEY_ID=shiplet', 'AWS_SECRET_ACCESS_KEY=secretsecret', 'AWS_DEFAULT_REGION=us-east-1', 'AWS_BUCKET=local', 'AWS_ENDPOINT=http://minio:9000', 'AWS_USE_PATH_STYLE_ENDPOINT=true', '');
    }

    return lines.join('\n');
}

// ── nginx config per template ─────────────────────────────────────────────────
function generateNginxConf(template) {
    const root = template === 'laravel' ? '/var/www/html/public'
        : template === 'symfony' ? '/var/www/html/public'
            : template === 'wordpress' ? '/var/www/html'
                : '/var/www/html/public';

    const index = template === 'wordpress' ? 'index.php index.html' : 'index.php';

    return `server {
    listen 80;
    server_name localhost;
    root ${root};
    index ${index};
    charset utf-8;
    client_max_body_size 100M;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \\.php$ {
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }
}
`;
}

// ── php.ini for development ───────────────────────────────────────────────────
function generatePhpIni() {
    return `; Shiplet — PHP development configuration
[PHP]
display_errors         = On
display_startup_errors = On
error_reporting        = E_ALL
html_errors            = Off
log_errors             = On
error_log              = /var/log/php_errors.log

; Performance
memory_limit          = 256M
max_execution_time    = 300
max_input_time        = 300
post_max_size         = 100M
upload_max_filesize   = 100M
max_file_uploads      = 20

; OPcache (development — validates every request)
opcache.enable        = 1
opcache.memory_consumption = 128
opcache.revalidate_freq    = 0

; Timezone
date.timezone = UTC
`;
}

// ── Supervisor config for Laravel workers ────────────────────────────────────
function generateSupervisorConf() {
    return `[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=/usr/local/sbin/php-fpm
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/worker.log
stopwaitsecs=3600

[program:laravel-scheduler]
command=php /var/www/html/artisan schedule:work
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/scheduler.log
`;
}

// ── shiplet.config.json for PHP projects ────────────────────────────────────────
function phpShipletConfig(answers) {
    return {
        language: 'php',
        runtime: answers.runtime || 'docker',
        appName: answers.appName,
        phpVersion: answers.phpVersion || '8.3',
        template: answers.template,
        webServer: answers.webServer || 'nginx',
        port: answers.port || 80,
    };
}

// ── helpers ───────────────────────────────────────────────────────────────────
function indent(str, spaces) {
    return str.split('\n')
        .map(l => (l.trim() ? ' '.repeat(spaces) + l : l))
        .join('\n');
}

module.exports = {
    generatePhpCompose,
    generatePhpDockerfile,
    generatePhpEnvAdditions,
    generateNginxConf,
    generatePhpIni,
    generateSupervisorConf,
    phpShipletConfig,
    phpServiceSnippet,
    PHP_IMAGES,
    PHP_EXTENSIONS,
};
