'use strict';

/**
 * Generate compose.yml content based on init answers.
 */
function generateCompose(answers) {
    const {
        appName,
        nodeVersion,
        packageManager,
        port,
        services = [],
        timezone,
    } = answers;

    const name = appName.toLowerCase().replace(/[^a-z0-9-]/g, '-');

    const serviceBlocks = services
        .map((s) => serviceSnippet(s))
        .filter(Boolean)
        .map((s) => indent(s, 2))
        .join('\n\n');

    const depends = services.length
        ? `\n    depends_on:\n${services.map((s) => `      - ${s}`).join('\n')}`
        : '';

    const networkNames = ['shiplet'];
    const networksBlock = networkNames.map((n) => `  ${n}:\n    driver: bridge`).join('\n');

    return `# Generated by Shiplet — https://github.com/anandpilania/shiplet
# Edit this file to customise your environment.

name: ${name}

services:
  app:
    build:
      context: .
      dockerfile: .shiplet/Dockerfile
      args:
        NODE_VERSION: "${nodeVersion}"
        PACKAGE_MANAGER: "${packageManager}"
        TZ: "${timezone}"
    image: ${name}/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "\${APP_PORT:-${port}}:${port}"
    volumes:
      - ".:/var/www/html"
      - "shiplet_node_modules:/var/www/html/node_modules"
    networks:
      - shiplet
    environment:
      TZ: "\${TZ:-${timezone}}"
      NODE_ENV: "\${NODE_ENV:-development}"${depends}
    restart: unless-stopped
    tty: true
    stdin_open: true

${serviceBlocks}
volumes:
  shiplet_node_modules:
    driver: local
${services.filter(hasVolume).map((s) => `  ${s}_data:\n    driver: local`).join('\n')}

networks:
${networksBlock}
`;
}

const WITH_VOLUME = new Set(['postgres', 'mysql', 'mongo', 'mongodb', 'minio', 'elasticsearch']);
function hasVolume(s) { return WITH_VOLUME.has(s); }

/**
 * Generate the Dockerfile for the app service.
 */
function generateDockerfile(answers) {
    const { nodeVersion = '20', packageManager = 'npm', timezone = 'UTC' } = answers;

    const pmSetup = {
        npm: '# npm is built in',
        yarn: 'RUN corepack enable && corepack prepare yarn@stable --activate',
        pnpm: 'RUN corepack enable && corepack prepare pnpm@latest --activate',
    }[packageManager] || '# npm is built in';

    return `# Auto-generated by Shiplet
ARG NODE_VERSION=${nodeVersion}
FROM node:\${NODE_VERSION}-bookworm-slim

ARG PACKAGE_MANAGER=npm
ARG TZ=UTC
ENV TZ=\${TZ}
ENV DEBIAN_FRONTEND=noninteractive

# System deps
RUN apt-get update -y \\
 && apt-get install -y --no-install-recommends \\
      curl git ca-certificates tzdata \\
 && ln -snf /usr/share/zoneinfo/\$TZ /etc/localtime \\
 && echo "\$TZ" > /etc/timezone \\
 && apt-get clean \\
 && rm -rf /var/lib/apt/lists/*

# Package manager setup
${pmSetup}

# Working directory
WORKDIR /var/www/html

# Default command — override in compose or with shiplet exec
CMD ["node", "index.js"]
`;
}

/**
 * Generate additions for the .env file.
 */
function generateEnvAdditions(answers) {
    const lines = ['# Shiplet'];
    lines.push(`APP_PORT=${answers.port || 3000}`);
    lines.push(`NODE_ENV=development`);
    lines.push(`TZ=${answers.timezone || 'UTC'}`);

    const s = answers.services || [];

    if (s.includes('postgres')) {
        lines.push('', '# PostgreSQL');
        lines.push('POSTGRES_USER=shiplet');
        lines.push('POSTGRES_PASSWORD=secret');
        lines.push('POSTGRES_DB=app');
        lines.push('DATABASE_URL=postgresql://shiplet:secret@postgres:5432/app');
    }
    if (s.includes('mysql')) {
        lines.push('', '# MySQL');
        lines.push('MYSQL_ROOT_PASSWORD=secret');
        lines.push('MYSQL_DATABASE=app');
        lines.push('MYSQL_USER=shiplet');
        lines.push('MYSQL_PASSWORD=secret');
        lines.push('DATABASE_URL=mysql://shiplet:secret@mysql:3306/app');
    }
    if (s.includes('mongo')) {
        lines.push('', '# MongoDB');
        lines.push('MONGO_INITDB_ROOT_USERNAME=shiplet');
        lines.push('MONGO_INITDB_ROOT_PASSWORD=secret');
        lines.push('MONGO_INITDB_DATABASE=app');
        lines.push('MONGODB_URI=mongodb://shiplet:secret@mongo:27017/app?authSource=admin');
    }
    if (s.includes('redis')) {
        lines.push('', '# Redis');
        lines.push('REDIS_URL=redis://redis:6379');
    }
    if (s.includes('mailpit')) {
        lines.push('', '# Mailpit');
        lines.push('SMTP_HOST=mailpit');
        lines.push('SMTP_PORT=1025');
    }
    if (s.includes('minio')) {
        lines.push('', '# MinIO (S3)');
        lines.push('MINIO_ROOT_USER=shiplet');
        lines.push('MINIO_ROOT_PASSWORD=secretsecret');
        lines.push('S3_ENDPOINT=http://minio:9000');
        lines.push('S3_BUCKET=local');
        lines.push('S3_ACCESS_KEY=shiplet');
        lines.push('S3_SECRET_KEY=secretsecret');
    }

    return lines.join('\n');
}

/**
 * Return a YAML snippet for a given service name.
 */
function serviceSnippet(name) {
    const snippets = {
        postgres: `postgres:
    image: "postgres:16-alpine"
    environment:
      POSTGRES_USER: "\${POSTGRES_USER:-shiplet}"
      POSTGRES_PASSWORD: "\${POSTGRES_PASSWORD:-secret}"
      POSTGRES_DB: "\${POSTGRES_DB:-app}"
    ports:
      - "\${POSTGRES_PORT:-5432}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-shiplet}"]
      interval: 10s
      retries: 5`,

        mysql: `mysql:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "\${MYSQL_ROOT_PASSWORD:-secret}"
      MYSQL_DATABASE: "\${MYSQL_DATABASE:-app}"
      MYSQL_USER: "\${MYSQL_USER:-shiplet}"
      MYSQL_PASSWORD: "\${MYSQL_PASSWORD:-secret}"
    ports:
      - "\${MYSQL_PORT:-3306}:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5`,

        mongo: `mongo:
    image: "mongo:7"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "\${MONGO_INITDB_ROOT_USERNAME:-shiplet}"
      MONGO_INITDB_ROOT_PASSWORD: "\${MONGO_INITDB_ROOT_PASSWORD:-secret}"
      MONGO_INITDB_DATABASE: "\${MONGO_INITDB_DATABASE:-app}"
    ports:
      - "\${MONGO_PORT:-27017}:27017"
    volumes:
      - "mongo_data:/data/db"
    networks:
      - shiplet`,

        redis: `redis:
    image: "redis:7-alpine"
    ports:
      - "\${REDIS_PORT:-6379}:6379"
    networks:
      - shiplet
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5`,

        mailpit: `mailpit:
    image: "axllent/mailpit"
    ports:
      - "\${MAILPIT_SMTP_PORT:-1025}:1025"
      - "\${MAILPIT_UI_PORT:-8025}:8025"
    networks:
      - shiplet`,

        minio: `minio:
    image: "minio/minio"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "\${MINIO_ROOT_USER:-shiplet}"
      MINIO_ROOT_PASSWORD: "\${MINIO_ROOT_PASSWORD:-secretsecret}"
    ports:
      - "\${MINIO_PORT:-9000}:9000"
      - "\${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - "minio_data:/data"
    networks:
      - shiplet`,

        elasticsearch: `elasticsearch:
    image: "elasticsearch:8.12.2"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "\${ELASTICSEARCH_PORT:-9200}:9200"
    volumes:
      - "elasticsearch_data:/usr/share/elasticsearch/data"
    networks:
      - shiplet`,

        adminer: `adminer:
    image: "adminer"
    ports:
      - "\${ADMINER_PORT:-8080}:8080"
    networks:
      - shiplet`,
    };

    return snippets[name] || null;
}

function indent(str, spaces) {
    return str
        .split('\n')
        .map((l) => (l.trim() ? ' '.repeat(spaces) + l : l))
        .join('\n');
}

module.exports = {
    generateCompose,
    generateDockerfile,
    generateEnvAdditions,
    serviceSnippet,
};
