'use strict';

/**
 * shiplet completions [bash|zsh|fish]
 *
 * Outputs shell completion script for the given shell.
 * Install with:
 *   bash:  shiplet completions bash >> ~/.bashrc && source ~/.bashrc
 *   zsh:   shiplet completions zsh  >> ~/.zshrc  && source ~/.zshrc
 *   fish:  shiplet completions fish > ~/.config/fish/completions/shiplet.fish
 */

const chalk = require('chalk');
const { header, info } = require('../utils/helpers');

const COMMANDS = [
    'init', 'up', 'down', 'build', 'shell', 'exec', 'node', 'npm', 'npx',
    'yarn', 'pnpm', 'test', 'logs', 'status', 'db', 'share', 'add',
    'publish', 'env', 'health', 'lint', 'scale', 'snapshot', 'release',
    'runtime', 'completions', 'upgrade',
];

const SERVICES = ['postgres', 'mysql', 'mongo', 'redis', 'mailpit', 'minio', 'elasticsearch', 'adminer'];

// ── Bash ──────────────────────────────────────────────────────────────────────
function bashScript() {
    return `
# Shiplet bash completions
# Generated by: shiplet completions bash
_shiplet_completions() {
  local cur="\${COMP_WORDS[COMP_CWORD]}"
  local prev="\${COMP_WORDS[COMP_CWORD-1]}"
  local commands="${COMMANDS.join(' ')}"

  case "\$prev" in
    shiplet)
      COMPREPLY=( \$(compgen -W "\$commands" -- "\$cur") )
      return ;;
    shell|exec|logs|db|health)
      COMPREPLY=( \$(compgen -W "app ${SERVICES.join(' ')}" -- "\$cur") )
      return ;;
    add)
      COMPREPLY=( \$(compgen -W "${SERVICES.join(' ')}" -- "\$cur") )
      return ;;
    env)
      COMPREPLY=( \$(compgen -W "get set unset list sync" -- "\$cur") )
      return ;;
    snapshot)
      COMPREPLY=( \$(compgen -W "save restore list delete" -- "\$cur") )
      return ;;
    runtime)
      COMPREPLY=( \$(compgen -W "show switch check" -- "\$cur") )
      return ;;
    release)
      COMPREPLY=( \$(compgen -W "patch minor major" -- "\$cur") )
      return ;;
    completions)
      COMPREPLY=( \$(compgen -W "bash zsh fish" -- "\$cur") )
      return ;;
  esac

  COMPREPLY=( \$(compgen -W "\$commands" -- "\$cur") )
}

complete -F _shiplet_completions shiplet
`.trimStart();
}

// ── Zsh ───────────────────────────────────────────────────────────────────────
function zshScript() {
    const cmds = COMMANDS.map((c) => `'${c}'`).join('\n      ');
    const svcs = ['app', ...SERVICES].map((s) => `'${s}'`).join('\n      ');

    return `
# Shiplet zsh completions
# Generated by: shiplet completions zsh
#compdef shiplet

_shiplet() {
  local state

  _arguments \\
    '1: :->command' \\
    '*: :->args'

  case $state in
    command)
      local -a commands
      commands=(
        ${cmds}
      )
      _describe 'shiplet commands' commands
      ;;
    args)
      case $words[2] in
        shell|exec|logs|db|health)
          local -a services
          services=(${svcs})
          _describe 'services' services ;;
        add)
          local -a add_services
          add_services=(${SERVICES.map((s) => `'${s}'`).join(' ')})
          _describe 'services' add_services ;;
        env)
          local -a env_actions
          env_actions=('get' 'set' 'unset' 'list' 'sync')
          _describe 'env actions' env_actions ;;
        snapshot)
          local -a snap_actions
          snap_actions=('save' 'restore' 'list' 'delete')
          _describe 'snapshot actions' snap_actions ;;
        runtime)
          local -a rt_actions
          rt_actions=('show' 'switch' 'check')
          _describe 'runtime actions' rt_actions ;;
        release)
          local -a bumps
          bumps=('patch' 'minor' 'major')
          _describe 'version bump' bumps ;;
        completions)
          local -a shells
          shells=('bash' 'zsh' 'fish')
          _describe 'shell' shells ;;
      esac
      ;;
  esac
}

_shiplet
`.trimStart();
}

// ── Fish ──────────────────────────────────────────────────────────────────────
function fishScript() {
    const cmdLines = COMMANDS.map(
        (c) => `complete -c shiplet -f -n '__fish_use_subcommand' -a '${c}'`
    ).join('\n');

    const svcLines = ['shell', 'exec', 'logs', 'db', 'health']
        .map((cmd) =>
            SERVICES.concat(['app'])
                .map((s) => `complete -c shiplet -f -n '__fish_seen_subcommand_from ${cmd}' -a '${s}'`)
                .join('\n')
        )
        .join('\n');

    return `
# Shiplet fish completions
# Generated by: shiplet completions fish
${cmdLines}

# Service completions
${svcLines}

# env sub-actions
complete -c shiplet -f -n '__fish_seen_subcommand_from env' -a 'get set unset list sync'

# snapshot sub-actions
complete -c shiplet -f -n '__fish_seen_subcommand_from snapshot' -a 'save restore list delete'

# runtime sub-actions
complete -c shiplet -f -n '__fish_seen_subcommand_from runtime' -a 'show switch check'

# release bumps
complete -c shiplet -f -n '__fish_seen_subcommand_from release' -a 'patch minor major'
`.trimStart();
}

module.exports = function completionsCommand(shell) {
    if (!shell) {
        header('Shell Completions');
        info('Usage:');
        console.log(`
  ${chalk.cyan('# Bash')}
  shiplet completions bash >> ~/.bashrc && source ~/.bashrc

  ${chalk.cyan('# Zsh')}
  shiplet completions zsh >> ~/.zshrc && source ~/.zshrc

  ${chalk.cyan('# Fish')}
  shiplet completions fish > ~/.config/fish/completions/shiplet.fish
    `);
        return;
    }

    switch (shell.toLowerCase()) {
        case 'bash': process.stdout.write(bashScript()); break;
        case 'zsh': process.stdout.write(zshScript()); break;
        case 'fish': process.stdout.write(fishScript()); break;
        default:
            console.error(chalk.red(`Unknown shell: ${shell}. Use bash, zsh, or fish.`));
            process.exit(1);
    }
};
